In [1]:
import pandas as pd
from sklearn.model_selection import KFold

In [2]:
df = pd.read_csv('./cow_bite_links_1407_transrac.csv')
df.rename(columns={'Unnamed: 0': ''}, inplace=True)

In [3]:
df.head()

,,type,name,count,L1,L2,L3,L4,L5,L6,...,L127,L128,L129,L130,L131,L132,L133,L134,L135,L136
0,0,cow_bite,1cd30bf7a77bbfaaf85acb2b27da587a74e5951067ba96...,8,8,37,37.0,60.0,60.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,cow_bite,2f4338b600baddf8b021162744427b9faaf7ec28230638...,29,1,21,21.0,40.0,40.0,58.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,cow_bite,3c86acfbc4289cc6d83adc3268a97e3eb2ecf1316d731b...,34,14,36,36.0,60.0,60.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,cow_bite,6bad72b6e29e294f91508e5dbcc3b762e42c9103ddcf6e...,12,10,31,31.0,50.0,50.0,69.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,cow_bite,6f9416bb9789f27385491d3b308c52f2c5a441038301fc...,1,0,26,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Initialize KFold with 10 splits
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Create 10-fold splits
fold = 1
for train_index, valid_index in kf.split(df):
    train_df = df.iloc[train_index]
    valid_df = df.iloc[valid_index]
    
    # Save the train and valid DataFrames as CSV files
    train_df.to_csv(f'train_fold_{fold}.csv', index=False)
    valid_df.to_csv(f'valid_fold_{fold}.csv', index=False)
    
    fold += 1

print("10-fold cross-validation splits have been created and saved as CSV files.")

10-fold cross-validation splits have been created and saved as CSV files.